name: Build and Release

on:
  push:
    branches:
      - main

jobs:
  release-linux-amd64:
    name: release linux/amd64
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: wangyoucao577/go-release-action@v1
        with:
          github_token: ${{ secrets.MY_GITHUB_TOKEN }}
          goos: linux
          goarch: amd64
          binary_name: neiasit
          project_path: ./cmd/cli/