name: Release

on:
  push:
    tags:
      - 'v*'

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        goos: [linux, windows, freebsd, openbsd]
        goarch: [amd64, arm64, 386, arm]
        exclude:
          - goos: windows
            goarch: arm
          - goos: windows
            goarch: arm64
          - goos: freebsd
            goarch: 386
          - goos: freebsd
            goarch: arm
          - goos: openbsd
            goarch: 386
          - goos: openbsd
            goarch: arm

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Go
        uses: actions/setup-go@v2
        with:
          go-version: 1.22.5

      - name: Build CLI
        run: |
          GOOS=${{ matrix.goos }} GOARCH=${{ matrix.goarch }} \
          go build -o neiasit${{ matrix.goos == 'windows' && '.exe' || '' }} ./cmd/cli

      - name: Archive neiasit binary
        run: |
          zip neiasit-${{ matrix.goos }}-${{ matrix.goarch }}.zip neiasit${{ matrix.goos == 'windows' && '.exe' || '' }}

      - name: Upload Artifacts
        uses: actions/upload-artifact@v2
        with:
          name: neiasit-${{ matrix.goos }}-${{ matrix.goarch }}
          path: neiasit-${{ matrix.goos }}-${{ matrix.goarch }}.zip

  test:
    needs: build
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest]
        include:
          - os: ubuntu-latest
            goos: linux
            goarch: amd64
          - os: ubuntu-latest
            goos: linux
            goarch: arm64
          - os: ubuntu-latest
            goos: linux
            goarch: arm
          - os: windows-latest
            goos: windows
            goarch: amd64
          - os: windows-latest
            goos: windows
            goarch: 386
          - os: ubuntu-latest
            goos: freebsd
            goarch: amd64
          - os: ubuntu-latest
            goos: freebsd
            goarch: arm64
          - os: ubuntu-latest
            goos: openbsd
            goarch: amd64
          - os: ubuntu-latest
            goos: openbsd
            goarch: arm64

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Download Artifact
        uses: actions/download-artifact@v2
        with:
          name: neiasit-${{ matrix.goos }}-${{ matrix.goarch }}
          path: .

      - name: Extract Artifact on Linux
        if: matrix.os == 'ubuntu-latest'
        run: unzip neiasit-${{ matrix.goos }}-${{ matrix.goarch }}.zip

      - name: Extract Artifact on Windows
        if: matrix.os == 'windows-latest'
        run: Expand-Archive -Path neiasit-${{ matrix.goos }}-${{ matrix.goarch }}.zip -DestinationPath .

      - name: Run CLI on Linux
        if: matrix.os == 'ubuntu-latest'
        run: ./neiasit --help

      - name: Run CLI on Windows
        if: matrix.os == 'windows-latest'
        run: ./neiasit.exe --help

  release:
    needs: [build, test]
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Download Artifact for Linux amd64
        uses: actions/download-artifact@v2
        with:
          name: neiasit-linux-amd64
          path: .

      - name: Download Artifact for Linux arm64
        uses: actions/download-artifact@v2
        with:
          name: neiasit-linux-arm64
          path: .

      - name: Download Artifact for Linux arm
        uses: actions/download-artifact@v2
        with:
          name: neiasit-linux-arm
          path: .

      - name: Download Artifact for Windows amd64
        uses: actions/download-artifact@v2
        with:
          name: neiasit-windows-amd64
          path: .

      - name: Download Artifact for Windows 386
        uses: actions/download-artifact@v2
        with:
          name: neiasit-windows-386
          path: .

      - name: Download Artifact for FreeBSD amd64
        uses: actions/download-artifact@v2
        with:
          name: neiasit-freebsd-amd64
          path: .

      - name: Download Artifact for FreeBSD arm64
        uses: actions/download-artifact@v2
        with:
          name: neiasit-freebsd-arm64
          path: .

      - name: Download Artifact for OpenBSD amd64
        uses: actions/download-artifact@v2
        with:
          name: neiasit-openbsd-amd64
          path: .

      - name: Download Artifact for OpenBSD arm64
        uses: actions/download-artifact@v2
        with:
          name: neiasit-openbsd-arm64
          path: .

      - name: Create Release
        id: create_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.MY_GITHUB_TOKEN }}
        with:
          tag_name: ${{ github.ref }}
          release_name: Release ${{ github.ref }}
          draft: false
          prerelease: false

      - name: Upload Release Asset for Linux amd64
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.MY_GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: ./neiasit-linux-amd64.zip
          asset_name: neiasit-linux-amd64.zip
          asset_content_type: application/zip

      - name: Upload Release Asset for Linux arm64
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.MY_GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: ./neiasit-linux-arm64.zip
          asset_name: neiasit-linux-arm64.zip
          asset_content_type: application/zip

      - name: Upload Release Asset for Linux arm
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.MY_GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: ./neiasit-linux-arm.zip
          asset_name: neiasit-linux-arm.zip
          asset_content_type: application/zip

      - name: Upload Release Asset for Windows amd64
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.MY_GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: ./neiasit-windows-amd64.zip
          asset_name: neiasit-windows-amd64.zip
          asset_content_type: application/zip

      - name: Upload Release Asset for Windows 386
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.MY_GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: ./neiasit-windows-386.zip
          asset_name: neiasit-windows-386.zip
          asset_content_type: application/zip

      - name: Upload Release Asset for FreeBSD amd64
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.MY_GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: ./neiasit-freebsd-amd64.zip
          asset_name: neiasit-freebsd-amd64.zip
          asset_content_type: application/zip

      - name: Upload Release Asset for FreeBSD arm64
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.MY_GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: ./neiasit-freebsd-arm64.zip
          asset_name: neiasit-freebsd-arm64.zip
          asset_content_type: application/zip

      - name: Upload Release Asset for OpenBSD amd64
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.MY_GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: ./neiasit-openbsd-amd64.zip
          asset_name: neiasit-openbsd-amd64.zip
          asset_content_type: application/zip

      - name: Upload Release Asset for OpenBSD arm64
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.MY_GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: ./neiasit-openbsd-arm64.zip
          asset_name: neiasit-openbsd-arm64.zip
          asset_content_type: application/zip
