name: Release

on:
  push:
    tags:
      - 'v*'

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        goos: [linux, darwin, windows]
        goarch: [amd64]

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Go
        uses: actions/setup-go@v2
        with:
          go-version: 1.22.5

      - name: Build CLI
        run: |
          GOOS=${{ matrix.goos }} GOARCH=${{ matrix.goarch }} go build -o neiasit-${{ matrix.goos }}-${{ matrix.goarch }} ./cmd/cli

      - name: Archive neiasit binary
        run: |
          zip neiasit-${{ matrix.goos }}-${{ matrix.goarch }}.zip neiasit-${{ matrix.goos }}-${{ matrix.goarch }}

      - name: Create Release
        id: create_release
        if: matrix.goos == 'linux' && matrix.goarch == 'amd64'
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.MY_GITHUB_TOKEN }}
        with:
          tag_name: ${{ github.ref }}
          release_name: Release ${{ github.ref }}
          draft: false
          prerelease: false

      - name: Upload Release Asset for Linux
        if: matrix.goos == 'linux'
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.MY_GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: ./neiasit-linux-amd64.zip
          asset_name: neiasit-linux-amd64.zip
          asset_content_type: application/zip

      - name: Upload Release Asset for macOS
        if: matrix.goos == 'darwin'
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.MY_GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: ./neiasit-darwin-amd64.zip
          asset_name: neiasit-darwin-amd64.zip
          asset_content_type: application/zip

      - name: Upload Release Asset for Windows
        if: matrix.goos == 'windows'
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.MY_GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: ./neiasit-windows-amd64.zip
          asset_name: neiasit-windows-amd64.zip
          asset_content_type: application/zip
